# sudo: required
language: node_js
services:
  - docker
  - postgresql
  - mysql
  - redis-server
  - mongodb
  - elasticsearch
  - rabbitmq
  - memcached
node_js:
  - "node"
  - "10"
  - "8"
  - "6"
  - "4"
# jobs:
#   include:
#     - node_js: "node"
before_install:
  - mysql -e 'CREATE DATABASE db;'
script: docker-compose up -d && yarn test
