version: '2'
services:
  postgres:
    image: postgres:9.5-alpine
    ports:
      - '127.0.0.1:5432:5432'
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    ports:
      - "127.0.0.1:3306:3306"
  redis:
    image: redis:4.0-alpine
    ports:
      - "127.0.0.1:6379:6379"
  mongo:
    image: mongo:3.6
    ports:
      - "127.0.0.1:27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    ports:
      - "127.0.0.1:9200:9200"
  rabbitmq:
    image: rabbitmq:3.6-alpine
    ports:
      - "127.0.0.1:5672:5672"
  qpid:
    image: scholzj/qpid-cpp:1.38.0
    command: -p 5673
    environment:
      - QPIDD_ADMIN_USERNAME=admin
      - QPIDD_ADMIN_PASSWORD=admin
    ports:
      - "127.0.0.1:5673:5673"
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "test.topic:1:1"
    ports:
      - "9092:9092"
