version: 2.1

orbs:
  win: circleci/windows@2.4.0

executors:
  linux:
    parameters:
      node-version:
        default: "latest"
        type: string
    docker:
      - image: node:<<parameters.version>>
    resource_class: small
  windows: win/default

jobs:
  core:
    parameters:
      os:
        type: string
      version:
        type: string
        default: "latest"
    executor:
      name: <<parameters.os>>
      node-version: <<parameters.version>>
    working_directory: ~/dd-trace-js
    steps:
      - checkout
      - &yarn-versions
        run:
          name: Versions
          command: yarn versions
      - &restore-yarn-cache
        restore_cache:
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - &yarn-install
        run:
          name: Install dependencies
          command: yarn install --ignore-engines
      - &save-yarn-cache
        save_cache:
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./yarn.lock
      - &yarn-rebuild
        run:
          name: Compile native code
          command: yarn rebuild
      - &yarn-test-core
        run:
          name: Unit tests
          command: yarn test:core:ci
      # - run:
      #     name: Merge coverage report
      #     command: yarn cover:merge
      # - store_artifacts:
      #     path: ./coverage
      # - persist_to_workspace:
      #     root: ~/dd-trace-js
      #     paths:
      #       - .nyc_merge/*

workflows:
  version: 2
  test:
    jobs:
      - core:
          matrix:
            parameters:
              os: [linux]
              version: ["8", "10", "12", "14", "16"]
      - core:
          matrix:
            parameters:
              os: [windows]
