on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
        node: [8, 10, 12]
    container: node:12-alpine
    name: A job to say hello
    steps:
    - name: Hello world action step
      run: echo "Hello, World!"
